version: '3.4'

services:
  application:
    image: halive/ogwc:latest
    environment:
      REDIS_ADDR: redis:6379
    ports:
    - "127.0.0.1:16666:16666"
  database:
    image: redis:latest
    volumes:
    - "redis_data:/data"
volumes:
  redis_data:
